version: "3.7"
services:
  goobi:
    # using build/context/dockerfile instead of the official image from DockerHub (custom fixes)
    # image: intranda/goobi-workflow:default-plugins
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: goobi_metadata
        target: /opt/digiverso/goobi/metadata
      - type: volume
        source: goobi_exportfolder
        target: /opt/digiverso/viewer/hotfolder
      
      - type: bind
        source: ./goobi-plugins
        target: /opt/digiverso/goobi/plugins

      - type: bind
        source: ./goobi-config
        target: /opt/digiverso/goobi/config

      # - type: bind
      #   source: ./goobi-data 
      #   target: /opt/digiverso/goobi/data

    depends_on: 
      - goobi-db

  goobi-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: goobi
      MYSQL_DATABASE: goobi
      MYSQL_USER: goobi
      MYSQL_PASSWORD: goobi
    volumes:
      - type: bind
        source: ./install/db/goobi_blank.sql
        target: /docker-entrypoint-initdb.d/goobi_blank.sql
      - type: volume
        source: goobi_dbdata
        target: /var/lib/mysql


volumes:
  goobi_metadata:
  goobi_dbdata:
  goobi_exportfolder:
